# Site settings
title: Ollis Blog
email: ollimi85@gmail.com
description: "My Blog about Java, AngularJS and whatever comes to mind."
baseurl: ""
url: "http://oliver-milke.de"
twitter_username: OliverMilke
github_username:  omilke

# Build settings
markdown: kramdown
permalink: /:title
