# Site settings
title: Ollis Blog
email: dev@oliver-milke.de
description: "My Blog about Java and whatever is on my radar."
baseurl: ""
url: "http://oliver-milke.de"
twitter_username: OliverMilke
github_username:  omilke

# Build settings
markdown: kramdown
permalink: /:title.html

sass:
    style: compressed